/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-06-24 06:37:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.BT3;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class chitiet_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/BT3/inc/footer.jsp", Long.valueOf(1592971729920L));
    _jspx_dependants.put("/views/BT3/inc/leftmenu.jsp", Long.valueOf(1592980477096L));
    _jspx_dependants.put("/views/BT3/inc/header.jsp", Long.valueOf(1592979663072L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>VinaEnter Edu - Web tin tức</title>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.10.1.min.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<meta name=\"robots\" content=\"index, follow\" />\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("\tcontent=\"tin tuc viet nhat, tin tức việt nhật, tin nhật bản, tin nhat ban\" />\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("\tcontent=\"Tin tức Việt - Nhật, cập nhật liên tục hằng ngày\" />\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/styles.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<a name=\"totop\"></a>\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t\t<div id=\"top-nav\">\r\n");
      out.write("\t\t\t<div class=\"main-content\">\r\n");
      out.write("\t\t\t\t<p class=\"fl\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/lien-he/\" title=\"\">TRUNG TÂM ĐÀO TẠO VINAENTER\r\n");
      out.write("\t\t\t\t\t\tEDU</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"fr mail-icon\">\r\n");
      out.write("\t\t\t\t\t<a href=\"\" title=\"\">HOT line: 0909.123.456 - 064.3456.789</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"top-menu\">\r\n");
      out.write("\t\t\t<div class=\"main-content\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"parent current\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/index.jsp\">Trang\r\n");
      out.write("\t\t\t\t\t\t\tchủ</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"parent\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/gioithieu.jsp\">Giới thiệu</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"parent\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/lienhe.jsp\">Liên hệ</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>");
      out.write("\r\n");
      out.write("<div id=\"main-body\">\r\n");
      out.write("\t<div class=\"main-content\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<div class=\"body-left fl\">\r\n");
      out.write("\t\t\t\t\t<div class=\"left-menu\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"parent\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/danhmuc.jsp\">Toàn cảnh\r\n");
      out.write("\t\t\t\t\t\t\t\t\tNhật Bản</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"parent\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/danhmuc.jsp\">Tin tức\r\n");
      out.write("\t\t\t\t\t\t\t\t\tViệt - Nhật</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"parent\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/danhmuc.jsp\">Tin tức\r\n");
      out.write("\t\t\t\t\t\t\t\t\tgiải trí</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"parent\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/danhmuc.jsp\">Du học\r\n");
      out.write("\t\t\t\t\t\t\t\t\tNhật Bản</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"support\">\r\n");
      out.write("\t\t\t\t\t\t<p>Hỗ trợ trực tuyến</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"yahoo\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"ymsgr:sendIM?trandangx\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Chat with Mr.Xuân\">Mr.Xuân</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"ymsgr:sendIM?itsontran\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Chat with Mr.Sơn\">Mr.Sơn</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<div cl\r\n");
      out.write("\t\t\t\t\t\t\tass=\"clr\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"skype\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"Skype:trandangx?chat\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Chat with Mr.Xuân\">Mr.Xuân</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"Skype:itsontran?chat\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Chat with Mr.Sơn\">Mr.Sơn</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"orther\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\tEmail: <span>vinaenter@gmail.com</span>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\tSố điện thoại: <span>0903154678</span>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"advs\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\" title=\"\"> <img src=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/images/qc1.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</a> <a href=\"\" title=\"\"> <img src=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/images/qc2.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>");
      out.write("\r\n");
      out.write("\t\t<div class=\"body-right fr\">\r\n");
      out.write("\t\t\t<div class=\"news-block detail\">\r\n");
      out.write("\t\t\t\t<h1 class=\"title\">Thị trấn truyền thống Uchiko – Nhật Bản</h1>\r\n");
      out.write("\t\t\t\t<p class=\"cat-date\">\r\n");
      out.write("\t\t\t\t\t<a title=\"Toàn cảnh Nhật Bản\" href=\"/Toan-canh-Nhat-Ban-c1/\">Toàn\r\n");
      out.write("\t\t\t\t\t\tcảnh Nhật Bản</a> <span>Cập nhật: 24/01/2014</span>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<div class=\"content-detail\">\r\n");
      out.write("\t\t\t\t\t<p\r\n");
      out.write("\t\t\t\t\t\tstyle=\"padding-top: 1em; padding-bottom: 1em; outline: none; list-style: none; border-style: none; color: rgb(51, 51, 51); font-family: Arial; font-size: 14px; line-height: 21px;\">\r\n");
      out.write("\t\t\t\t\t\t<span\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"outline: none; list-style: none; border-style: none; font-size: medium;\">Thị\r\n");
      out.write("\t\t\t\t\t\t\ttrấn truyền thống của Uchiko được bao quanh bởi vẻ đẹp tự nhiên\r\n");
      out.write("\t\t\t\t\t\t\tvà có vị trí khoảng 42 km về phía tây nam của Matsuyama trong\r\n");
      out.write("\t\t\t\t\t\t\ttỉnh Ehime .Có ba suối chạy qua khu vực: Oda, các Nakayama và\r\n");
      out.write("\t\t\t\t\t\t\tFumoto. Uchiko có vài khu vực bằng phẳng và khoảng 70% diện tích\r\n");
      out.write("\t\t\t\t\t\t\tđất là rừng. Đất màu mỡ và các ngành công nghiệp chính là nông\r\n");
      out.write("\t\t\t\t\t\t\tnghiệp , đặc biệt là lá thuốc lá , nấm đông cô nấm , và các loại\r\n");
      out.write("\t\t\t\t\t\t\ttrái cây như quả hồng , nho và lê nashi . Các bờ sông được sử\r\n");
      out.write("\t\t\t\t\t\t\tdụng chủ yếu bởi các trang trại và đất nông nghiệp có thể mở rộng\r\n");
      out.write("\t\t\t\t\t\t\tđến những ngọn đồi và các sườn núi dốc. Tính đến tháng 4 năm\r\n");
      out.write("\t\t\t\t\t\t\t2005, dân số trong Uchiko là khoảng 20,650. Quanh năm, cảnh quan\r\n");
      out.write("\t\t\t\t\t\t\ttuyệt đẹp và, núi màu mỡ rất xanh và thung lũng cho người dân\r\n");
      out.write("\t\t\t\t\t\t\tUchiko nuôi dưỡng nền kinh tế.</span>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<p\r\n");
      out.write("\t\t\t\t\t\tstyle=\"padding-top: 1em; padding-bottom: 1em; outline: none; list-style: none; border-style: none; color: rgb(51, 51, 51); font-family: Arial; font-size: 14px; line-height: 21px;\">\r\n");
      out.write("\t\t\t\t\t\t<span\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"outline: none; list-style: none; border-style: none; font-size: medium;\">Từ\r\n");
      out.write("\t\t\t\t\t\t\tkhi kết thúc thời kỳ Edo (1603-1867) để kết thúc thời kỳ Minh Trị\r\n");
      out.write("\t\t\t\t\t\t\t(1868-1912), Uchiko phát triển và phát triển mạnh như một trung\r\n");
      out.write("\t\t\t\t\t\t\ttâm sản xuất của Nhật Bản giấy và sáp . Vào thời điểm đó huyện\r\n");
      out.write("\t\t\t\t\t\t\tyokaichi và Gokoku trở thành công nghiệp hóa và nhà lịch sử của\r\n");
      out.write("\t\t\t\t\t\t\thọ vẫn còn giữ lại một số di tích vinh quang trước đây của\r\n");
      out.write("\t\t\t\t\t\t\tUchiko.</span>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"orther-detail\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"orther-news\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"title orther-icon\">Các tin khác</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"items\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/Den-thieng-Sefa-Utaki-o-Okinawa-a218.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Đền thiêng Sefa Utaki ở Okinawa\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Đền thiêng Sefa Utaki ở Okinawa\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"images/Seifa-utaki.jpg\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"/Den-thieng-Sefa-Utaki-o-Okinawa-a218.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle=\"Đền thiêng Sefa Utaki ở Okinawa\">Đền thiêng Sefa\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tUtaki ở Okinawa</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/Cay-cau-lon-Seto-Naikai-a217.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Cây cầu lớn Seto Naikai\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Cây cầu lớn Seto Naikai\" src=\"images/Seto-Naikai.jpg\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"/Cay-cau-lon-Seto-Naikai-a217.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle=\"Cây cầu lớn Seto Naikai\">Cây cầu lớn Seto Naikai</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"/Nhung-bao-tang-co-mot-khong-hai-o-Nhat-Ban-a216.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Những bảo tàng có một không hai ở Nhật Bản\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Những bảo tàng có một không hai ở Nhật Bản\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"images/baotangthuoclavamuoi-tokyo.jpg\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"/Nhung-bao-tang-co-mot-khong-hai-o-Nhat-Ban-a216.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle=\"Những bảo tàng có một không hai ở Nhật Bản\">Những\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tbảo tàng có một không hai ở</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"/Thieu-nu-Nhat-Ban-xinh-tuoi-don-le-Thanh-nhan-a215.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Thiếu nữ Nhật Bản xinh tươi đón lễ Thành nhân\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Thiếu nữ Nhật Bản xinh tươi đón lễ Thành nhân\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"images/thieununhatban-lethanhnhan.jpg\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"/Thieu-nu-Nhat-Ban-xinh-tuoi-don-le-Thanh-nhan-a215.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle=\"Thiếu nữ Nhật Bản xinh tươi đón lễ Thành nhân\">Thiếu\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tnữ Nhật Bản xinh tươi đón lễ</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"items-noimg\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"/Tam-nuoc-lanh-om-tang-bang-lon-de-cau-may-a214.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Tắm nước lạnh, ôm tảng băng lớn để cầu may\">Tắm nước\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tlạnh, ôm tảng băng lớn để</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"/‘Quan-Geisha’-o-Kyoto-va-nhung-chuyen-chua-biet-a213.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"‘Quận Geisha’ ở Kyoto và những chuyện chưa biết\">‘Quận\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tGeisha’ ở Kyoto và những chuyện</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"/Luot-buyt-va-nghĩ-vè-van-minh-ỏ-Kyoto-a212.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"“Lướt buýt” và nghĩ về văn minh ở Kyoto\">“Lướt\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tbuýt” và nghĩ về văn minh</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"/Cam-hinh-ngu-giac-mang-lai-may-man-o-Nhat-Ban-a211.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Cam hình ngũ giác mang lại may mắn ở Nhật Bản\">Cam\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thình ngũ giác mang lại may mắn ở</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/Mua-xuan-sang-co-hoa-anh-dao-a210.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Mùa xuân sang có hoa anh đào...\">Mùa xuân sang có\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thoa anh đào...</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/Mua-xuan-sang-co-hoa-anh-dao-a210.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Mùa xuân sang có hoa anh đào...\">Mùa xuân sang có\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thoa anh đào...</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/Mua-xuan-sang-co-hoa-anh-dao-a210.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Mùa xuân sang có hoa anh đào...\">Mùa xuân sang có\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thoa anh đào...</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/Mua-xuan-sang-co-hoa-anh-dao-a210.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Mùa xuân sang có hoa anh đào...\">Mùa xuân sang có\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thoa anh đào...</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/Mua-xuan-sang-co-hoa-anh-dao-a210.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Mùa xuân sang có hoa anh đào...\">Mùa xuân sang có\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thoa anh đào...</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/Mua-xuan-sang-co-hoa-anh-dao-a210.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Mùa xuân sang có hoa anh đào...\">Mùa xuân sang có\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thoa anh đào...</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("\t\t\t<div class=\"main-content\">\r\n");
      out.write("\t\t\t\t<p class=\"fl\">\r\n");
      out.write("\t\t\t\t\tCopyright &copy; 2017. <span>VinaEnter Edu</span> giữ toàn\r\n");
      out.write("\t\t\t\t\tquyền.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<div class=\"search fl\">&nbsp;</div>\r\n");
      out.write("\t\t\t\t<div class=\"backtotop fr\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#totop\" title=\"\">Về đầu trang</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
