/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-06-24 06:39:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.BT3;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class danhmuc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/BT3/inc/footer.jsp", Long.valueOf(1592971729920L));
    _jspx_dependants.put("/views/BT3/inc/leftmenu.jsp", Long.valueOf(1592980477096L));
    _jspx_dependants.put("/views/BT3/inc/header.jsp", Long.valueOf(1592979663072L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>VinaEnter Edu - Web tin tức</title>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.10.1.min.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<meta name=\"robots\" content=\"index, follow\" />\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("\tcontent=\"tin tuc viet nhat, tin tức việt nhật, tin nhật bản, tin nhat ban\" />\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("\tcontent=\"Tin tức Việt - Nhật, cập nhật liên tục hằng ngày\" />\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/styles.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<a name=\"totop\"></a>\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t\t<div id=\"top-nav\">\r\n");
      out.write("\t\t\t<div class=\"main-content\">\r\n");
      out.write("\t\t\t\t<p class=\"fl\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/lien-he/\" title=\"\">TRUNG TÂM ĐÀO TẠO VINAENTER\r\n");
      out.write("\t\t\t\t\t\tEDU</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"fr mail-icon\">\r\n");
      out.write("\t\t\t\t\t<a href=\"\" title=\"\">HOT line: 0909.123.456 - 064.3456.789</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"top-menu\">\r\n");
      out.write("\t\t\t<div class=\"main-content\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"parent current\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/index.jsp\">Trang\r\n");
      out.write("\t\t\t\t\t\t\tchủ</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"parent\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/gioithieu.jsp\">Giới thiệu</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"parent\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/lienhe.jsp\">Liên hệ</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>");
      out.write("\r\n");
      out.write("\t\t<div id=\"main-body\">\r\n");
      out.write("\t\t\t<div class=\"main-content\">\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<div class=\"body-left fl\">\r\n");
      out.write("\t\t\t\t\t<div class=\"left-menu\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"parent\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/danhmuc.jsp\">Toàn cảnh\r\n");
      out.write("\t\t\t\t\t\t\t\t\tNhật Bản</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"parent\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/danhmuc.jsp\">Tin tức\r\n");
      out.write("\t\t\t\t\t\t\t\t\tViệt - Nhật</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"parent\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/danhmuc.jsp\">Tin tức\r\n");
      out.write("\t\t\t\t\t\t\t\t\tgiải trí</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"parent\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/danhmuc.jsp\">Du học\r\n");
      out.write("\t\t\t\t\t\t\t\t\tNhật Bản</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"support\">\r\n");
      out.write("\t\t\t\t\t\t<p>Hỗ trợ trực tuyến</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"yahoo\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"ymsgr:sendIM?trandangx\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Chat with Mr.Xuân\">Mr.Xuân</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"ymsgr:sendIM?itsontran\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Chat with Mr.Sơn\">Mr.Sơn</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<div cl\r\n");
      out.write("\t\t\t\t\t\t\tass=\"clr\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"skype\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"Skype:trandangx?chat\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Chat with Mr.Xuân\">Mr.Xuân</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"Skype:itsontran?chat\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Chat with Mr.Sơn\">Mr.Sơn</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"orther\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\tEmail: <span>vinaenter@gmail.com</span>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\tSố điện thoại: <span>0903154678</span>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"advs\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\" title=\"\"> <img src=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/images/qc1.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</a> <a href=\"\" title=\"\"> <img src=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/images/qc2.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"body-right fr\">\r\n");
      out.write("\t\t\t\t\t<div class=\"news-block\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"title-cat\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/Toan-canh-Nhat-Ban-c1/\" title=\"Toàn cảnh Nhật Bản\">Toàn\r\n");
      out.write("\t\t\t\t\t\t\t\tcảnh Nhật Bản</a>\r\n");
      out.write("\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"content-cat1\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item-top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-left fl\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"chitiet.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"Thị trấn truyền thống Uchiko – Nhật Bản\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"images/thitran-Uchiko-nhatban.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Thị trấn truyền thống Uchiko – Nhật Bản\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-right-cat fr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/chitiet.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"Thị trấn truyền thống Uchiko – Nhật Bản\" class=\"title\">Thị\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttrấn truyền thống Uchiko – Nhật Bản</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"margin: 10px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"preview\">Thị trấn truyền thống của Uchiko được\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tbao quanh bởi vẻ đẹp tự nhiên và có vị trí khoảng 42 km về\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tphía tây nam của Matsuyama trong tỉnh Ehime .Có ba suối chạy\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tqua khu vực: Oda, các Nakayama và Fumoto.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-left fl\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/chitiet.jsp\" title=\"Đền thiêng Sefa Utaki ở Okinawa\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/Seifa-utaki.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Đền thiêng Sefa Utaki ở Okinawa\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-right-cat fr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/chitiet.jsp\" title=\"Đền thiêng Sefa Utaki ở Okinawa\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"title\">Đền thiêng Sefa Utaki ở Okinawa</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"margin: 10px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"preview\">Sefa Utaki nằm ở phía đông nam của đảo\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tOkinawa Honto , khoảng 15 km từ Naha. Seifa-utaki là một đền\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tThần đạo. Đây là một phần của Di sản thế giới của UNESCO nằm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttrên địa bàn Nanjō, Okinawa. Nó nằm trên một sườn\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tđồi&nbsp;&nbsp;dày</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-left fl\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"/Cay-cau-lon-Seto-Naikai-a217.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"Cây cầu lớn Seto Naikai\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"images/Seto-Naikai.jpg\" alt=\"Cây cầu lớn Seto Naikai\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-right-cat fr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"/Cay-cau-lon-Seto-Naikai-a217.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"Cây cầu lớn Seto Naikai\" class=\"title\">Cây cầu lớn\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tSeto Naikai</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"margin: 10px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"preview\">Người ta có thể đáp xe lửa nhanh chóng\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttừ Hokkaido lạnh như Sibir, xuyên qua Honshu đến bến cảng\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tKyushu khí hậu á nhiệt đới và đền miếu khói hương nhộn nhịp\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttrên đảo Shikoku phía Nam. Chiếc cầu mới bắc ngang Seto Naikai\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t– Biển Trong</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-left fl\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"/Nhung-bao-tang-co-mot-khong-hai-o-Nhat-Ban-a216.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"Những bảo tàng có một không hai ở Nhật Bản\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"images/baotangthuoclavamuoi-tokyo.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Những bảo tàng có một không hai ở Nhật Bản\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-right-cat fr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"/Nhung-bao-tang-co-mot-khong-hai-o-Nhat-Ban-a216.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"Những bảo tàng có một không hai ở Nhật Bản\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"title\">Những bảo tàng có một không hai ở Nhật Bản</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"margin: 10px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"preview\">Bảo tàng thuốc lá và muối hay bảo tàng\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tTakoyaki chỉ là hai trong số nhiều bảo tàng ấn tượng tại Nhật\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tBản sẽ góp phần làm chuyến đi của bạn thêm hấp dẫn.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-left fl\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"/Thieu-nu-Nhat-Ban-xinh-tuoi-don-le-Thanh-nhan-a215.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"Thiếu nữ Nhật Bản xinh tươi đón lễ Thành nhân\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"images/thieununhatban-lethanhnhan.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Thiếu nữ Nhật Bản xinh tươi đón lễ Thành nhân\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-right-cat fr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"/Thieu-nu-Nhat-Ban-xinh-tuoi-don-le-Thanh-nhan-a215.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"Thiếu nữ Nhật Bản xinh tươi đón lễ Thành nhân\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"title\">Thiếu nữ Nhật Bản xinh tươi đón lễ Thành\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tnhân</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"margin: 10px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"preview\">Lễ thành nhân – buổi lễ dành cho thanh\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tniên bước sang tuổi 20 (tuổi trưởng thành tại Nhật Bản) – được\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tcoi là một trong những ngày lễ đặc biệt nhất tại đất nước Mặt\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttrời mọc.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-left fl\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"/Tam-nuoc-lanh-om-tang-bang-lon-de-cau-may-a214.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"Tắm nước lạnh, ôm tảng băng lớn để cầu may\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"images/tamnuoclanh-ombang_nhatban-1.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Tắm nước lạnh, ôm tảng băng lớn để cầu may\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-right-cat fr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"/Tam-nuoc-lanh-om-tang-bang-lon-de-cau-may-a214.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"Tắm nước lạnh, ôm tảng băng lớn để cầu may\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"title\">Tắm nước lạnh, ôm tảng băng lớn để cầu may</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"margin: 10px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"preview\">Nhiệt độ ngoài trời khi đó vào khoảng 6\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tđộ C, những người đàn ông cởi bỏ y phục, chỉ mặc trên mình một\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tchiếc khố truyền thống mỏng manh. Họ cùng đầm mình xuống một\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tbể nước lạnh, được đặt trước đền Teppozu Inari</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-left fl\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"/‘Quan-Geisha’-o-Kyoto-va-nhung-chuyen-chua-biet-a213.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"‘Quận Geisha’ ở Kyoto và những chuyện chưa biết\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"images/quan_Geisha_tokyo.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"‘Quận Geisha’ ở Kyoto và những chuyện chưa biết\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-right-cat fr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"/‘Quan-Geisha’-o-Kyoto-va-nhung-chuyen-chua-biet-a213.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"‘Quận Geisha’ ở Kyoto và những chuyện chưa biết\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"title\">‘Quận Geisha’ ở Kyoto và những chuyện chưa\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tbiết</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"margin: 10px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"preview\">Để khám phá nghệ thuật giải trí truyền\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tthống nổi tiếng của Nhật Bản – Geisha, du khách có thể tìm đến\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tcác “quận geisha” ở Kyoto.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-left fl\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"/Luot-buyt-va-nghĩ-vè-van-minh-ỏ-Kyoto-a212.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"“Lướt buýt” và nghĩ về văn minh ở Kyoto\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"images/giaothongnhatban-bus.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"“Lướt buýt” và nghĩ về văn minh ở Kyoto\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-right-cat fr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"/Luot-buyt-va-nghĩ-vè-van-minh-ỏ-Kyoto-a212.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"“Lướt buýt” và nghĩ về văn minh ở Kyoto\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"title\">“Lướt buýt” và nghĩ về văn minh ở Kyoto</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"margin: 10px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"preview\">Dường như người Nhật “không đi xe gắn\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmáy”, bởi lẽ đi xe buýt tiện lợi hơn, nhanh hơn, tiết kiệm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thơn, và an toàn hơn. Đây cũng là lý do tại sao giao thông\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tNhật Bản luôn thông thoáng, hiếm khi xảy ra tai nạn, ít tiếng\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tồn dù các</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-left fl\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"/Cam-hinh-ngu-giac-mang-lai-may-man-o-Nhat-Ban-a211.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"Cam hình ngũ giác mang lại may mắn ở Nhật Bản\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"images/cam-hinh-ngu-giac-mang-lai-may-man-o-nhat-ban-2.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Cam hình ngũ giác mang lại may mắn ở Nhật Bản\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-right-cat fr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"/Cam-hinh-ngu-giac-mang-lai-may-man-o-Nhat-Ban-a211.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"Cam hình ngũ giác mang lại may mắn ở Nhật Bản\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"title\">Cam hình ngũ giác mang lại may mắn ở Nhật\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tBản</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"margin: 10px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"preview\">Cụm từ “Gokaku noIyokan” có nghĩa là\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t“mùi hương ngọt ngào của thành công trong các kỳ thi”. Chính\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvì vậy cam iyokan hay “Gokaku no Iyokan” được coi như một món\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tquà mang lại may mắn cho các sinh viên trong mùa thi sắp tới ở\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tYawatahama,</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-left fl\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"/Mua-xuan-sang-co-hoa-anh-dao-a210.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"Mùa xuân sang có hoa anh đào...\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"images/hoa-anh-dao.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Mùa xuân sang có hoa anh đào...\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-right-cat fr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"/Mua-xuan-sang-co-hoa-anh-dao-a210.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"Mùa xuân sang có hoa anh đào...\" class=\"title\">Mùa\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\txuân sang có hoa anh đào...</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"margin: 10px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"preview\">Hoa anh đào có 3 màu là màu trắng, hồng\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvà đỏ. Thời gian tồn tại của một bông hoa anh đào thường kéo\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdài từ 7 đến 15 ngày, trung bình là khoảng 1 tuần. Tùy theo\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttừng chủng loại hoa và điều kiện môi trường thời tiết mà tuổi\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tthọ</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pager\">\r\n");
      out.write("\t\t\t\t\t\t\t<style>\r\n");
      out.write(".page-blue a {\r\n");
      out.write("\tpadding: 3px 7px;\r\n");
      out.write("\tborder: 1px solid green;\r\n");
      out.write("\tbackground: green;\r\n");
      out.write("\tcolor: #FFF;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".page-blue a:hover {\r\n");
      out.write("\tpadding: 3px 7px;\r\n");
      out.write("\tborder: 1px solid #144879;\r\n");
      out.write("\tbackground: #144879;\r\n");
      out.write("\tcolor: #FFF;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".page-blue .nav-current-page {\r\n");
      out.write("\tpadding: 3px 7px;\r\n");
      out.write("\tborder: 1px solid #144879;\r\n");
      out.write("\tbackground: #144879;\r\n");
      out.write("\tcolor: #FFF;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"page-blue\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"nav-current-page\">1</span> <a href=\"\">2</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"\">2</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("\t\t\t<div class=\"main-content\">\r\n");
      out.write("\t\t\t\t<p class=\"fl\">\r\n");
      out.write("\t\t\t\t\tCopyright &copy; 2017. <span>VinaEnter Edu</span> giữ toàn\r\n");
      out.write("\t\t\t\t\tquyền.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<div class=\"search fl\">&nbsp;</div>\r\n");
      out.write("\t\t\t\t<div class=\"backtotop fr\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#totop\" title=\"\">Về đầu trang</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
