/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-06-24 06:35:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.BT3;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/BT3/inc/footer.jsp", Long.valueOf(1592971729920L));
    _jspx_dependants.put("/views/BT3/inc/leftmenu.jsp", Long.valueOf(1592980477096L));
    _jspx_dependants.put("/views/BT3/inc/header.jsp", Long.valueOf(1592979663072L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>VinaEnter Edu - Web tin tức</title>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.10.1.min.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<meta name=\"robots\" content=\"index, follow\" />\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("\tcontent=\"tin tuc viet nhat, tin tức việt nhật, tin nhật bản, tin nhat ban\" />\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("\tcontent=\"Tin tức Việt - Nhật, cập nhật liên tục hằng ngày\" />\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/styles.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<a name=\"totop\"></a>\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t\t<div id=\"top-nav\">\r\n");
      out.write("\t\t\t<div class=\"main-content\">\r\n");
      out.write("\t\t\t\t<p class=\"fl\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/lien-he/\" title=\"\">TRUNG TÂM ĐÀO TẠO VINAENTER\r\n");
      out.write("\t\t\t\t\t\tEDU</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"fr mail-icon\">\r\n");
      out.write("\t\t\t\t\t<a href=\"\" title=\"\">HOT line: 0909.123.456 - 064.3456.789</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"top-menu\">\r\n");
      out.write("\t\t\t<div class=\"main-content\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"parent current\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/index.jsp\">Trang\r\n");
      out.write("\t\t\t\t\t\t\tchủ</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"parent\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/gioithieu.jsp\">Giới thiệu</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"parent\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/lienhe.jsp\">Liên hệ</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>");
      out.write("\r\n");
      out.write("<div id=\"main-body\">\r\n");
      out.write("\t<div class=\"main-content\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<div class=\"body-left fl\">\r\n");
      out.write("\t\t\t\t\t<div class=\"left-menu\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"parent\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/danhmuc.jsp\">Toàn cảnh\r\n");
      out.write("\t\t\t\t\t\t\t\t\tNhật Bản</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"parent\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/danhmuc.jsp\">Tin tức\r\n");
      out.write("\t\t\t\t\t\t\t\t\tViệt - Nhật</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"parent\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/danhmuc.jsp\">Tin tức\r\n");
      out.write("\t\t\t\t\t\t\t\t\tgiải trí</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"parent\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/danhmuc.jsp\">Du học\r\n");
      out.write("\t\t\t\t\t\t\t\t\tNhật Bản</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"support\">\r\n");
      out.write("\t\t\t\t\t\t<p>Hỗ trợ trực tuyến</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"yahoo\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"ymsgr:sendIM?trandangx\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Chat with Mr.Xuân\">Mr.Xuân</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"ymsgr:sendIM?itsontran\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Chat with Mr.Sơn\">Mr.Sơn</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<div cl\r\n");
      out.write("\t\t\t\t\t\t\tass=\"clr\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"skype\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"Skype:trandangx?chat\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Chat with Mr.Xuân\">Mr.Xuân</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"Skype:itsontran?chat\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Chat with Mr.Sơn\">Mr.Sơn</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"orther\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\tEmail: <span>vinaenter@gmail.com</span>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\tSố điện thoại: <span>0903154678</span>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"advs\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\" title=\"\"> <img src=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/images/qc1.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</a> <a href=\"\" title=\"\"> <img src=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT3/images/qc2.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>");
      out.write("\r\n");
      out.write("\t\t<div class=\"body-right fr\">\r\n");
      out.write("\t\t\t<div class=\"news-block\">\r\n");
      out.write("\t\t\t\t<h2 class=\"title-cat\">\r\n");
      out.write("\t\t\t\t\t<a href=\"danhmuc.jsp\" title=\"Toàn cảnh Nhật Bản\">Toàn cảnh Nhật\r\n");
      out.write("\t\t\t\t\t\tBản</a>\r\n");
      out.write("\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t<div class=\"content-cat\">\r\n");
      out.write("\t\t\t\t\t<div class=\"item-left fl\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"chitiet.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"Thị trấn truyền thống Uchiko – Nhật Bản\"><img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"images/thitran-Uchiko-nhatban.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"Thị trấn truyền thống Uchiko – Nhật Bản\" /></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"chitiet.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"Thị trấn truyền thống Uchiko – Nhật Bản\" class=\"title\">Thị\r\n");
      out.write("\t\t\t\t\t\t\ttrấn truyền thống Uchiko – Nhật Bản</a>\r\n");
      out.write("\t\t\t\t\t\t<p>Thị trấn truyền thống của Uchiko được bao quanh bởi vẻ đẹp\r\n");
      out.write("\t\t\t\t\t\t\ttự nhiên và có vị trí khoảng 42 km về phía tây nam của Matsuyama\r\n");
      out.write("\t\t\t\t\t\t\ttrong tỉnh</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item-right fr\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"chitiet.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle=\"Đền thiêng Sefa Utaki ở Okinawa\" class=\"title\">Đền\r\n");
      out.write("\t\t\t\t\t\t\t\t\tthiêng Sefa Utaki ở Okinawa</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"cat-date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"danhmuc.jsp\" title=\"Toàn cảnh Nhật Bản\">Toàn cảnh\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tNhật Bản</a> <span>Cập nhật: 24/01/2014</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"preview\">Sefa Utaki nằm ở phía đông nam của đảo\r\n");
      out.write("\t\t\t\t\t\t\t\t\tOkinawa Honto , khoảng 15 km từ Naha. Seifa-utaki là một đền\r\n");
      out.write("\t\t\t\t\t\t\t\t\tThần đạo. Đây là một phần của Di sản...</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"chitiet.jsp\" title=\"Cây cầu lớn Seto Naikai\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"title\">Cây cầu lớn Seto Naikai</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"cat-date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"/Toan-canh-Nhat-Ban-c1/\" title=\"Toàn cảnh Nhật Bản\">Toàn\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tcảnh Nhật Bản</a> <span>Cập nhật: 24/01/2014</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"preview\">Người ta có thể đáp xe lửa nhanh chóng từ\r\n");
      out.write("\t\t\t\t\t\t\t\t\tHokkaido lạnh như Sibir, xuyên qua Honshu đến bến cảng Kyushu\r\n");
      out.write("\t\t\t\t\t\t\t\t\tkhí hậu á nhiệt đới và đền miếu...</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"/Nhung-bao-tang-co-mot-khong-hai-o-Nhat-Ban-a216.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle=\"Những bảo tàng có một không hai ở Nhật Bản\" class=\"title\">Những\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbảo tàng có một không hai ở Nhật Bản</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"cat-date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"/Toan-canh-Nhat-Ban-c1/\" title=\"Toàn cảnh Nhật Bản\">Toàn\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tcảnh Nhật Bản</a> <span>Cập nhật: 24/01/2014</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"preview\">Bảo tàng thuốc lá và muối hay bảo tàng\r\n");
      out.write("\t\t\t\t\t\t\t\t\tTakoyaki chỉ là hai trong số nhiều bảo tàng ấn tượng tại Nhật\r\n");
      out.write("\t\t\t\t\t\t\t\t\tBản sẽ góp phần làm chuyến đi...</p></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"news-block\">\r\n");
      out.write("\t\t\t\t<h2 class=\"title-cat\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/Tin-tuc-Viet-Nhat-c2/\" title=\"Tin tức Việt - Nhật\">Tin\r\n");
      out.write("\t\t\t\t\t\ttức Việt - Nhật</a>\r\n");
      out.write("\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t<div class=\"content-cat\">\r\n");
      out.write("\t\t\t\t\t<div class=\"item-left fl\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/EVN-ngong-von-Nhat-Ban-a224.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"EVN ngóng vốn Nhật Bản\"><img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"images/evn ngong von.jpg\" alt=\"EVN ngóng vốn Nhật Bản\" /></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"/EVN-ngong-von-Nhat-Ban-a224.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"EVN ngóng vốn Nhật Bản\" class=\"title\">EVN ngóng vốn\r\n");
      out.write("\t\t\t\t\t\t\tNhật Bản</a>\r\n");
      out.write("\t\t\t\t\t\t<p>Đã có 12 dự án của ngành điện sử dụng nguồn vốn hỗ trợ phát\r\n");
      out.write("\t\t\t\t\t\t\ttriển chính thức &#40;ODA&#41; và vay tín dụng từ Nhật Bản, với\r\n");
      out.write("\t\t\t\t\t\t\tquy mô</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item-right fr\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/Dau-an-huu-nghi-Ha-Noi-Fukuoka-a223.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle=\"Dấu ấn hữu nghị Hà Nội - Fukuoka\" class=\"title\">Dấu\r\n");
      out.write("\t\t\t\t\t\t\t\t\tấn hữu nghị Hà Nội - Fukuoka</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"cat-date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"/Tin-tuc-Viet-Nhat-c2/\" title=\"Tin tức Việt - Nhật\">Tin\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttức Việt - Nhật</a> <span>Cập nhật: 24/01/2014</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"preview\">Trong khuôn khổ “Những ngày Fukuoka tại\r\n");
      out.write("\t\t\t\t\t\t\t\t\tHà Nội”, một loạt sự kiện văn hóa Nhật Bản đặc sắc đã để lại\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdấu ấn tốt đẹp cho...</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"/Cai-cach-de-thu-hut-von-dau-tu-Nhat-Ban-a222.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle=\"Cải cách để thu hút vốn đầu tư Nhật Bản\" class=\"title\">Cải\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcách để thu hút vốn đầu tư Nhật Bản</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"cat-date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"/Tin-tuc-Viet-Nhat-c2/\" title=\"Tin tức Việt - Nhật\">Tin\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttức Việt - Nhật</a> <span>Cập nhật: 24/01/2014</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"preview\">Sáng 5-9 tại Hà Nội diễn ra Diễn đàn Kinh\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttế cấp cao Việt Nam - Nhật Bản 2013 &#40;VJES&#41;. Đây là hoạt\r\n");
      out.write("\t\t\t\t\t\t\t\t\tđộng nhân kỷ niệm 40 năm quan hệ...</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/Tao-khac-biet-thu-hut-FDI-Nhat-Ban-a221.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle=\"Tạo khác biệt thu hút FDI Nhật Bản\" class=\"title\">Tạo\r\n");
      out.write("\t\t\t\t\t\t\t\t\tkhác biệt thu hút FDI Nhật Bản</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"cat-date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"/Tin-tuc-Viet-Nhat-c2/\" title=\"Tin tức Việt - Nhật\">Tin\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttức Việt - Nhật</a> <span>Cập nhật: 24/01/2014</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"preview\">Trong bối cảnh suy giảm kinh tế toàn cầu,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tngày càng có nhiều DN Nhật Bản tìm kiếm cơ hội đầu tư tại Việt\r\n");
      out.write("\t\t\t\t\t\t\t\t\tNam. Dòng vốn đầu tư của DN...</p></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"news-block\">\r\n");
      out.write("\t\t\t\t<h2 class=\"title-cat\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/Tin-tuc-giai-tri-c3/\" title=\"Tin tức giải trí\">Tin\r\n");
      out.write("\t\t\t\t\t\ttức giải trí</a>\r\n");
      out.write("\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t<div class=\"content-cat\">\r\n");
      out.write("\t\t\t\t\t<div class=\"item-left fl\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/Huyen-thoai-nu-chien-binh-Nhat-Ban-a229.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"Huyền thoại nữ chiến binh Nhật Bản\"><img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"images/nu-chien-binh-nhat-ban.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"Huyền thoại nữ chiến binh Nhật Bản\" /></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"/Huyen-thoai-nu-chien-binh-Nhat-Ban-a229.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"Huyền thoại nữ chiến binh Nhật Bản\" class=\"title\">Huyền\r\n");
      out.write("\t\t\t\t\t\t\tthoại nữ chiến binh Nhật Bản</a>\r\n");
      out.write("\t\t\t\t\t\t<p>Một số tài liệu gọi họ là những “samurai nữ” trong khi cách\r\n");
      out.write("\t\t\t\t\t\t\tdùng đúng nhất phải là ‘onna bu-geisha’ &#40;ở đây, onna là phụ\r\n");
      out.write("\t\t\t\t\t\t\tnữ còn</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item-right fr\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/Tinh-dung-gio-cua-nguoi-Nhat-a228.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle=\"Tính đúng giờ của người Nhật\" class=\"title\">Tính đúng\r\n");
      out.write("\t\t\t\t\t\t\t\t\tgiờ của người Nhật</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"cat-date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"/Tin-tuc-giai-tri-c3/\" title=\"Tin tức giải trí\">Tin\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttức giải trí</a> <span>Cập nhật: 24/01/2014</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"preview\">Xã hội phát triển thì ý niệm về giờ giấc\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcũng phải thay đổi để thích ứng với hoàn cảnh mới. Giữ đúng giờ\r\n");
      out.write("\t\t\t\t\t\t\t\t\thẹn là 1 đức tính công...</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/Con-so-xui-xeo-cua-nguoi-Nhat-a227.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle=\"Con số xui xẻo của người Nhật\" class=\"title\">Con số\r\n");
      out.write("\t\t\t\t\t\t\t\t\txui xẻo của người Nhật</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"cat-date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"/Tin-tuc-giai-tri-c3/\" title=\"Tin tức giải trí\">Tin\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttức giải trí</a> <span>Cập nhật: 24/01/2014</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"preview\">Ở Châu Âu và Mỹ, người ta tin rằng số 13\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmang lại những điều xui xẻo và thứ 6 ngày 13 là 1 ngày cực kỳ\r\n");
      out.write("\t\t\t\t\t\t\t\t\txui trong cuộc đời. Ở Anh, khách...</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"/Nhat-Ban-Lao-dong-la-tai-san-quy-gia-nhat-a226.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle=\"Nhật Bản: Lao động là tài sản quý giá nhất\" class=\"title\">Nhật\r\n");
      out.write("\t\t\t\t\t\t\t\t\tBản: Lao động là tài sản quý giá nhất</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"cat-date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"/Tin-tuc-giai-tri-c3/\" title=\"Tin tức giải trí\">Tin\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttức giải trí</a> <span>Cập nhật: 24/01/2014</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"preview\">Nhật Bản là nước nghèo về tài nguyên\r\n");
      out.write("\t\t\t\t\t\t\t\t\tkhoáng sản nên không thể làm giàu bằng tài nguyên thiên nhiên\r\n");
      out.write("\t\t\t\t\t\t\t\t\thay xuất khẩu nông sản như các nước...</p></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"news-block\">\r\n");
      out.write("\t\t\t\t<h2 class=\"title-cat\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/Du-hoc-Nhat-Ban-c4/\" title=\"Du học Nhật Bản\">Du học\r\n");
      out.write("\t\t\t\t\t\tNhật Bản</a>\r\n");
      out.write("\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t<div class=\"content-cat\">\r\n");
      out.write("\t\t\t\t\t<div class=\"item-left fl\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/Cam-nang-du-hoc-Nhat-Ban-2014-a234.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"Cẩm nang du học Nhật Bản 2014\"><img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"images/cam-nang.jpg\" alt=\"Cẩm nang du học Nhật Bản 2014\" /></a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/Cam-nang-du-hoc-Nhat-Ban-2014-a234.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"Cẩm nang du học Nhật Bản 2014\" class=\"title\">Cẩm nang\r\n");
      out.write("\t\t\t\t\t\t\tdu học Nhật Bản 2014</a>\r\n");
      out.write("\t\t\t\t\t\t<p>Du Học Nhật Bản Năm 2014 – Vì sao ngày càng nhiều các bạn\r\n");
      out.write("\t\t\t\t\t\t\ttrẻ lựa chọn Du Học Nhật ? Du Học Nhật Bản mang lại những lợi ích\r\n");
      out.write("\t\t\t\t\t\t\tgì?</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item-right fr\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/Du-hoc-Nhat-Ban-nhieu-loi-the-a233.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle=\"Du học Nhật Bản nhiều lợi thế\" class=\"title\">Du học\r\n");
      out.write("\t\t\t\t\t\t\t\t\tNhật Bản nhiều lợi thế</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"cat-date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"/Du-hoc-Nhat-Ban-c4/\" title=\"Du học Nhật Bản\">Du\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thọc Nhật Bản</a> <span>Cập nhật: 24/01/2014</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"preview\">Du học Nhật Bản ngoài việc học hỏi tri\r\n");
      out.write("\t\t\t\t\t\t\t\t\tthức, công nghệ, điều quan trọng là du học sinh học hỏi được\r\n");
      out.write("\t\t\t\t\t\t\t\t\tphong cách làm việc và ý thức kỷ...</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"/Suy-nghi-cua-du-hoc-sinh-tai-nhat-ve-Homestay-(O-nha-dan)-a232.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle=\"Suy nghĩ của du học sinh tại nhật về Homestay (Ở nhà dân)\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"title\">Suy nghĩ của du học sinh tại nhật về Homestay\r\n");
      out.write("\t\t\t\t\t\t\t\t\t(Ở nhà dân)</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"cat-date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"/Du-hoc-Nhat-Ban-c4/\" title=\"Du học Nhật Bản\">Du\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thọc Nhật Bản</a> <span>Cập nhật: 24/01/2014</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"preview\">Là một du học sinh đang đi du học tại\r\n");
      out.write("\t\t\t\t\t\t\t\t\tNhật Bản tôi đã homestay &#40;ở nhà dân&#41; một tuần với một\r\n");
      out.write("\t\t\t\t\t\t\t\t\tgia đình người Nhật đó là một...</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"/Du-hoc-Nhat-Ban-va-Tu-nghiep-Nhat-Ban-khac-nhau-nhu-the-nao-a231.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle=\"Du học Nhật Bản và Tu nghiệp Nhật Bản khác nhau như thế nào?\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"title\">Du học Nhật Bản và Tu nghiệp Nhật Bản khác\r\n");
      out.write("\t\t\t\t\t\t\t\t\tnhau như thế nào?</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"cat-date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"/Du-hoc-Nhat-Ban-c4/\" title=\"Du học Nhật Bản\">Du\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thọc Nhật Bản</a> <span>Cập nhật: 24/01/2014</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"preview\">Du học Nhật Bản và Tu nghiệp Nhật Bản\r\n");
      out.write("\t\t\t\t\t\t\t\t\tkhác nhau như thế nào? Hoa Sen sẽ so sánh về sự khác nhau giữa\r\n");
      out.write("\t\t\t\t\t\t\t\t\tDu học Nhật Bản và Tu nghiệp Nhật...</p></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("\t\t\t<div class=\"main-content\">\r\n");
      out.write("\t\t\t\t<p class=\"fl\">\r\n");
      out.write("\t\t\t\t\tCopyright &copy; 2017. <span>VinaEnter Edu</span> giữ toàn\r\n");
      out.write("\t\t\t\t\tquyền.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<div class=\"search fl\">&nbsp;</div>\r\n");
      out.write("\t\t\t\t<div class=\"backtotop fr\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#totop\" title=\"\">Về đầu trang</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
