/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-06-23 15:51:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.BT1;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class danhmuc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/BT1/inc/header.jsp", Long.valueOf(1592926085737L));
    _jspx_dependants.put("/views/BT1/inc/footer.jsp", Long.valueOf(1592917551236L));
    _jspx_dependants.put("/views/BT1/inc/leftbanner.jsp", Long.valueOf(1592926935416L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>VinaEnter EDU - Đã học là làm được</title>\r\n");
      out.write("\t<meta name=\"description\" content=\"Thiet ke website, dao tap lap trinh\">\r\n");
      out.write("\t<meta name=\"keywords\" content=\"thiet ke website, dao tap lap trinh\">\r\n");
      out.write("\t<link href=\"");
      out.print(request.getContextPath());
      out.write("/views/BT1/css/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"main\">\r\n");
      out.write("\t\t<div class=\"page\">\r\n");
      out.write("\t\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t\t<div class=\"header-img\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/views/BT1/images/header.jpg\" alt=\"\" width=\"800\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"topmenu\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/BT1/index.jsp\">Trang chủ</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/BT1/tintuc.jsp\">Tin tức</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>");
      out.write("\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("\t<div class=\"leftpanel\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<h2>Danh mục tin</h2>\r\n");
      out.write("<ul>\r\n");
      out.write("\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/BT1/danhmuc.jsp\">Thời sự</a></li>\r\n");
      out.write("\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT1/danhmuc.jsp\">Góc nhìn</a></li>\r\n");
      out.write("\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/BT1/danhmuc.jsp\">Thế giới</a></li>\r\n");
      out.write("\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/BT1/danhmuc.jsp\">Kinh doanh</a></li>\r\n");
      out.write("</ul>");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"rightpanel\">\r\n");
      out.write("\t\t<div class=\"rightbody\">\r\n");
      out.write("\t\t\t<h1 class=\"title\">Tin tá»©c >> Thá»i sá»±</h1>\r\n");
      out.write("\t\t\t<div class=\"items-new\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<h2>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\" title=\"\">Trung Quá»c Äiá»u thÃªm 17 tÃ u Äáº¿n\r\n");
      out.write("\t\t\t\t\t\t\t\tkhu vá»±c giÃ n khoan</a>\r\n");
      out.write("\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\" title=\"\"><img src=\"images/tmp/h1.jpg\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Äá» báº£o vá» giÃ n khoan, Trung Quá»c ÄÃ£ Äiá»u\r\n");
      out.write("\t\t\t\t\t\t\t\tthÃªm 17 tÃ u cÃ¡c loáº¡i so vá»i hÃ´m trÆ°á»c, sáºµn sÃ ng\r\n");
      out.write("\t\t\t\t\t\t\t\tÄÃ¢m va vÃ o tÃ u Viá»t Nam.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<h2>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\" title=\"\">Trá»ng tÃ i - váº¿t Äen cá»§a ká»³\r\n");
      out.write("\t\t\t\t\t\t\t\tWorld Cup sÃ´i Äá»ng </a>\r\n");
      out.write("\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\" title=\"\"><img src=\"images/tmp/h2.jpg\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t\t\t\t<p>World Cup 2014 chÆ°a Äi háº¿t lÆ°á»£t Äáº§u vÃ²ng báº£ng\r\n");
      out.write("\t\t\t\t\t\t\t\tnhÆ°ng cÃ¡c trá»ng tÃ i Äáº³ng cáº¥p FIFA ÄÃ£ cÃ³ tá»i bá»n\r\n");
      out.write("\t\t\t\t\t\t\t\ttráº­n bá» chá» trÃ­ch dá»¯ dá»i.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<h2>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\" title=\"\">Nhá»¯ng má»¹ nhÃ¢n Viá»t duyÃªn dÃ¡ng\r\n");
      out.write("\t\t\t\t\t\t\t\tá» tuá»i tá»© tuáº§n</a>\r\n");
      out.write("\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\" title=\"\"><img src=\"images/tmp/h4.jpg\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Äá» báº£o vá» giÃ n khoan, Trung Quá»c ÄÃ£ Äiá»u\r\n");
      out.write("\t\t\t\t\t\t\t\tthÃªm 17 tÃ u cÃ¡c loáº¡i so vá»i hÃ´m trÆ°á»c, sáºµn sÃ ng\r\n");
      out.write("\t\t\t\t\t\t\t\tÄÃ¢m va vÃ o tÃ u Viá»t Nam.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<h2>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\" title=\"\">Chuyá»n nhÆ°á»£ng 17/6: Arsenal mua\r\n");
      out.write("\t\t\t\t\t\t\t\tBalotelli, trÃ¡o hÃ ng Man Utd</a>\r\n");
      out.write("\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\" title=\"\"><img src=\"images/tmp/h5.jpg\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Äá»i bÃ³ng thÃ nh London Äang Äáº©y máº¡nh viá»c\r\n");
      out.write("\t\t\t\t\t\t\t\ttuyá»n lá»±a nhá»¯ng vá» trÃ­ cÃ²n yáº¿u trong Äá»i hÃ¬nh\r\n");
      out.write("\t\t\t\t\t\t\t\tá» cáº£ ba tuyáº¿n.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<h2>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\" title=\"\">ChuyÃªn gia Anh tin cháº¯c vá» trÃ­\r\n");
      out.write("\t\t\t\t\t\t\t\tMH370 rÆ¡i</a>\r\n");
      out.write("\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\" title=\"\"><img src=\"images/tmp/h1.jpg\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t\t\t\t<p>CÃ¡c chuyÃªn gia thuá»c cÃ´ng ty viá»n thÃ´ng Anh\r\n");
      out.write("\t\t\t\t\t\t\t\tInmarsat cho ráº±ng há» xÃ¡c Äá»nh ÄÆ°á»£c vá» trÃ­ chiáº¿c\r\n");
      out.write("\t\t\t\t\t\t\t\tmÃ¡y bay MH370 ÄÃ£ rÆ¡i xuá»ng trÃªn áº¤n Äá» DÆ°Æ¡ng, tuy\r\n");
      out.write("\t\t\t\t\t\t\t\tnhiÃªn Äá»i.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"paginator\">\r\n");
      out.write("\t\t\t\t\t<a href=\"\">Trang 1</a> | <a href=\"\" class=\"active\">Trang 2</a> | <a\r\n");
      out.write("\t\t\t\t\t\thref=\"\">Trang 3</a> | <a href=\"\">Trang 4</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"clr\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("\t\t\t\t<p>Trung tâm đào tạo Lập trình viên VinaEnter EDU</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
