/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-06-23 15:44:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.BT1;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/BT1/inc/header.jsp", Long.valueOf(1592926085737L));
    _jspx_dependants.put("/views/BT1/inc/footer.jsp", Long.valueOf(1592917551236L));
    _jspx_dependants.put("/views/BT1/inc/leftbanner.jsp", Long.valueOf(1592926935416L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>VinaEnter EDU - Đã học là làm được</title>\r\n");
      out.write("\t<meta name=\"description\" content=\"Thiet ke website, dao tap lap trinh\">\r\n");
      out.write("\t<meta name=\"keywords\" content=\"thiet ke website, dao tap lap trinh\">\r\n");
      out.write("\t<link href=\"");
      out.print(request.getContextPath());
      out.write("/views/BT1/css/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"main\">\r\n");
      out.write("\t\t<div class=\"page\">\r\n");
      out.write("\t\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t\t<div class=\"header-img\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/views/BT1/images/header.jpg\" alt=\"\" width=\"800\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"topmenu\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/BT1/index.jsp\">Trang chủ</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/BT1/tintuc.jsp\">Tin tức</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>");
      out.write("\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("\t<div class=\"leftpanel\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<h2>Danh mục tin</h2>\r\n");
      out.write("<ul>\r\n");
      out.write("\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/BT1/danhmuc.jsp\">Thời sự</a></li>\r\n");
      out.write("\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/BT1/danhmuc.jsp\">Góc nhìn</a></li>\r\n");
      out.write("\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/BT1/danhmuc.jsp\">Thế giới</a></li>\r\n");
      out.write("\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/BT1/danhmuc.jsp\">Kinh doanh</a></li>\r\n");
      out.write("</ul>");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"rightpanel\">\r\n");
      out.write("\t\t<div class=\"rightbody\">\r\n");
      out.write("\t\t\t<h1 class=\"title\">Giá»i thiá»u vá» chÃºng tÃ´i</h1>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<strong>VinaEnter</strong> thiáº¿t káº¿ website theo chuáº©n W3C,\r\n");
      out.write("\t\t\t\tthÃ´ng minh vÃ  tá»i Æ°u hÃ³a google: GiÃºp cho Google tÃ¬m tháº¥y\r\n");
      out.write("\t\t\t\tnhá»¯ng ná»i dung trang web cá»§a báº¡n dá» hÆ¡n, nhanh hÆ¡n vá»i\r\n");
      out.write("\t\t\t\tthá»© háº¡ng cao. Website táº£i NHANH, giao diá»n Äáº¸P, quáº£n\r\n");
      out.write("\t\t\t\ttrá» Dá» DÃNG, THÃN THIá»N vá»i ngÆ°á»i dÃ¹ng. TÃ­ch há»£p\r\n");
      out.write("\t\t\t\tcung cá»¥ thÃ´ng minh, nháº­n biáº¿t khÃ¡ch hÃ ng Äang muá»n gÃ¬,\r\n");
      out.write("\t\t\t\tÄá» ÄÆ°a ra chiáº¿n lÆ°á»£c bÃ¡n hÃ ng phÃ¹ há»£p.<br /> <br />\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>Giáº£i phÃ¡p quáº£ng bÃ¡ thÆ°Æ¡ng hiá»u, marketing online\r\n");
      out.write("\t\t\t\ttÄng lÆ°á»£ng truy cáº­p, ÄÆ°a khÃ¡ch hÃ ng tiá»m nÄng tá»i\r\n");
      out.write("\t\t\t\twebsite. KhÃ¡m bá»nh website, Äáº©y hÃ ng loáº¡t tá»« khÃ³a tiá»m\r\n");
      out.write("\t\t\t\tnÄng lÃªn TOP GOOGLE, tÄng nhanh doanh sá» bÃ¡n hÃ ng!</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("\t\t\t\t<p>Trung tâm đào tạo Lập trình viên VinaEnter EDU</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
