/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-06-24 03:26:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.BT2;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/BT2/inc/header.jsp", Long.valueOf(1592968671335L));
    _jspx_dependants.put("/views/BT2/inc/footer.jsp", Long.valueOf(1592967961576L));
    _jspx_dependants.put("/views/BT2/inc/menu.jsp", Long.valueOf(1592968799927L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>VinaEnter EDU - Đã học là làm được</title>\r\n");
      out.write("<meta name=\"description\" content=\"Thiet ke website, dao tap lap trinh\">\r\n");
      out.write("<meta name=\"keywords\" content=\"thiet ke website, dao tap lap trinh\">\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/views/BT2/css/style.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Header -->\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t<!-- Header. Status part -->\r\n");
      out.write("\t\t<div id=\"header-status\">\r\n");
      out.write("\t\t\t<div class=\"container_12\">\r\n");
      out.write("\t\t\t\t<div class=\"grid_4\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"user-pro\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">Logout</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>Chào, <a href=\"\">admin</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"clear: both;\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- End #header-status -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Header. Main part -->\r\n");
      out.write("\t\t<div id=\"header-main\">\r\n");
      out.write("\t\t\t<div class=\"container_12\">\r\n");
      out.write("\t\t\t\t<div class=\"grid_12\">\r\n");
      out.write("\t\t\t\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"nav\">\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"current\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/views/BT2/index.jsp\">Quản\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttrị</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/views/BT2/taikhoan.jsp\">Tài\r\n");
      out.write("\t\t\t\t\t\t\t\t\tkhoản</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- End. #Logo -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- End. .grid_12-->\r\n");
      out.write("\t\t\t\t<div style=\"clear: both;\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- End. .container_12 -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- End #header-main -->\r\n");
      out.write("\t\t<div style=\"clear: both;\"></div>");
      out.write("\r\n");
      out.write("            <!-- Sub navigation -->\r\n");
      out.write("            <div id=\"subnav\">\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("<div class=\"container_12\">\r\n");
      out.write("\t<div class=\"grid_12\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/BT2/list.jsp\">sản phẩm</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/BT2/list.jsp\">Danh mục sản phẩm</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/BT2/add.jsp\">Giới thiệu</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/BT2/list.jsp\">Đơn hàng</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/BT2/list.jsp\">Liên hệ</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End. .grid_12-->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- End. .container_12 -->");
      out.write("\r\n");
      out.write("                <div style=\"clear: both;\"></div>\r\n");
      out.write("            </div> <!-- End #subnav -->\r\n");
      out.write("        </div> <!-- End #header -->\r\n");
      out.write("        \r\n");
      out.write("\t\t<div class=\"container_12\">\r\n");
      out.write("            <!-- Form elements -->    \r\n");
      out.write("            <div class=\"grid_12\">\r\n");
      out.write("            \r\n");
      out.write("                <div class=\"module\">\r\n");
      out.write("                     <h2><span>Thêm tin tức</span></h2>\r\n");
      out.write("                        \r\n");
      out.write("                     <div class=\"module-body\">\r\n");
      out.write("                        <form action=\"\">\r\n");
      out.write("                        \r\n");
      out.write("                            <div>\r\n");
      out.write("                                <span class=\"notification n-success\">Thêm thành công</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <p>\r\n");
      out.write("                                <label>Thêm tin</label>\r\n");
      out.write("                                <input type=\"text\" class=\"input-medium\" />\r\n");
      out.write("                            </p>\r\n");
      out.write("                            \r\n");
      out.write("                            <p>\r\n");
      out.write("                                <label>Danh mục tin</label>\r\n");
      out.write("                                <select class=\"input-short\">\r\n");
      out.write("                                    <option value=\"1\">Option 1</option>\r\n");
      out.write("                                    <option value=\"2\">Option 2</option>\r\n");
      out.write("                                    <option value=\"3\">Option 3</option>\r\n");
      out.write("                                    <option value=\"4\">Option 4</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("                                <label>Hình ảnh</label>\r\n");
      out.write("                                <input type=\"file\" value=\"\" />\r\n");
      out.write("                            </p>\r\n");
      out.write("                            \r\n");
      out.write("                            <p>\r\n");
      out.write("                                <label>Mô tả</label>\r\n");
      out.write("                                <textarea rows=\"7\" cols=\"90\" class=\"input-medium\"></textarea>\r\n");
      out.write("                            </p>\r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            <p>\r\n");
      out.write("                                <label>Chi tiết</label>\r\n");
      out.write("                                <textarea rows=\"7\" cols=\"90\" class=\"input-long\"></textarea>\r\n");
      out.write("                            </p>\r\n");
      out.write("                                \r\n");
      out.write("                            <fieldset>\r\n");
      out.write("                                <input class=\"submit-green\" type=\"submit\" value=\"Thêm tin\" /> \r\n");
      out.write("                                <input class=\"submit-gray\" type=\"submit\" value=\"Nhập lại\" />\r\n");
      out.write("                            </fieldset>\r\n");
      out.write("                        </form>\r\n");
      out.write("                     </div> <!-- End .module-body -->\r\n");
      out.write("\r\n");
      out.write("                </div>  <!-- End .module -->\r\n");
      out.write("        \t\t<div style=\"clear:both;\"></div>\r\n");
      out.write("            </div> <!-- End .grid_12 -->\r\n");
      out.write("                \r\n");
      out.write("            <div style=\"clear:both;\"></div>\r\n");
      out.write("           \r\n");
      out.write("        <!-- Footer -->\r\n");
      out.write("       ");
      out.write("\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("        \t<div class=\"container_12\">\r\n");
      out.write("            \t<div class=\"grid_12\">\r\n");
      out.write("                \t<p>Copyright &copy; 2013. <a href=\"http://vinaenter.edu.vn\" title=\"Đã học là làm được\">VinaEnter EDU</a></p>\r\n");
      out.write("        \t\t</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div style=\"clear:both;\"></div>\r\n");
      out.write("        </div> <!-- End #footer -->\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
